title: Abwasser Stegesiedlung
description: Informationen zum Anschluss der Stegesiedlung an das öffentliche Kanalnetz
baseurl: ""
url: "https://abwasser.stegesiedlung.de"

theme: null
plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - sample.jpg
  - README.md
